# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

# Localized import of controller routes
controllers_localized:
    resource: ../src/Controller/
    type: attribute
    prefix: '/{_locale}'
    requirements:
        _locale: 'en|bg'

# Redirect root to the English homepage by default
root_home_redirect:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: app_home
        _locale: en
        permanent: false
